# Generated by Django 4.2.7 on 2025-04-03 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="date_ordered",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="digital",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
    ]
