# Generated by Django 4.2.7 on 2025-04-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_complete_order_date_ordered_product_digital_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
